version: 2

models:
  - name: dim_sensor
    columns:
      - name: sensor_id
        tests:
          - unique

      - name: store_id
        tests:
          - relationships:
              to: ref('dim_store')
              field: store_id
  - name: fact_daily_data
    columns:
      - name: store_id
        tests:
          - relationships:
              to: ref('dim_store')
              field: store_id

      - name: sensor_id
        tests:
          - relationships:
              to: ref('dim_sensor')
              field: sensor_id

      - name: IN_COUNT
        tests: 
          - positive_value

      - name: OUT_COUNT
        tests: 
          - positive_value

  - name: dim_date
    columns:
      - name: day_name
        tests:
          - accepted_values:
              values: ['Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday']
